/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mayukh Nair
 */

import com.darkprograms.speech.microphone.Microphone;
import com.darkprograms.speech.recognizer.GSpeechDuplex;
import com.darkprograms.speech.recognizer.GSpeechResponseListener;
import com.darkprograms.speech.recognizer.GoogleResponse;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javaFlacEncoder.FLACFileWriter;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import org.apache.commons.exec.*;



public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    public Client() 
    {
          initComponents();
          //this.setIconImage(new ImageIcon(getClass().getResource("/src/imglib/rocket 8bit.png")).getImage());
          jScrollPane1.setBorder(null);
          jScrollPane2.setBorder(null);
    }

    int xmouse,ymouse;
     Font isFocused=new Font("Segoe UI", Font.PLAIN,11);
     Font notfocused=new Font("Segoe UI", Font.ITALIC,11);
     public String filepat;
     public String filenam;
     public String pop;
     Connection con;
     static Statement st;
     static ResultSet ras;
     GSpeechDuplex duplo=new GSpeechDuplex("AIzaSyCnl6MRydhw_5fLXIdASxkLJzcJh5iX0M4");
     Microphone micra;
     File audiofil;
     
    
  
     
     
            
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FrameWindowBar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        fdev = new javax.swing.JTextField();
        floc = new javax.swing.JTextField();
        browsebutton = new javax.swing.JButton();
        SaveConfigButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listerine = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        fullscreencheck = new javax.swing.JCheckBox();
        keymappercheck = new javax.swing.JCheckBox();
        socketcheck = new javax.swing.JCheckBox();
        noconsolelog = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        guidebold = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        guidetext = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        micicon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        resp = new javax.swing.JLabel();
        conf = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DOSRocket");
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 1, true));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        FrameWindowBar.setBackground(new java.awt.Color(255, 255, 255));
        FrameWindowBar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        FrameWindowBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imglib/rocket 8bit.png"))); // NOI18N
        FrameWindowBar.setText("DOSRocket, the DOSBox front-end");
        FrameWindowBar.setToolTipText("DOSRocket-DOSBox Launcher");
        FrameWindowBar.setOpaque(true);
        FrameWindowBar.setPreferredSize(new java.awt.Dimension(60, 60));
        FrameWindowBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameWindowBarMouseDragged(evt);
            }
        });
        FrameWindowBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FrameWindowBarFocusLost(evt);
            }
        });
        FrameWindowBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FrameWindowBarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameWindowBarMousePressed(evt);
            }
        });
        FrameWindowBar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                FrameWindowBarComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add a game", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11), new java.awt.Color(0, 153, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Developer");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("Executable File Path");

        fname.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        fname.setForeground(new java.awt.Color(204, 204, 204));
        fname.setText("The name of the game");
        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameFocusLost(evt);
            }
        });

        fdev.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        fdev.setForeground(new java.awt.Color(204, 204, 204));
        fdev.setText("The developer/creator of the game");
        fdev.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fdevFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fdevFocusLost(evt);
            }
        });

        floc.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        floc.setForeground(new java.awt.Color(204, 204, 204));
        floc.setText("Where is the main .exe file of the game stored?");
        floc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                flocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                flocFocusLost(evt);
            }
        });

        browsebutton.setBackground(new java.awt.Color(255, 255, 255));
        browsebutton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        browsebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imglib/folder_256.png"))); // NOI18N
        browsebutton.setText("Browse");
        browsebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                browsebuttonMouseEntered(evt);
            }
        });
        browsebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebuttonActionPerformed(evt);
            }
        });

        SaveConfigButton.setBackground(new java.awt.Color(255, 255, 255));
        SaveConfigButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        SaveConfigButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imglib/spanner2.png"))); // NOI18N
        SaveConfigButton.setText("Save Configuration");
        SaveConfigButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveConfigButtonMouseEntered(evt);
            }
        });
        SaveConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveConfigButtonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton2.setText("Run game");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SaveConfigButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(floc, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browsebutton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fdev)
                            .addComponent(fname)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fdev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(browsebutton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SaveConfigButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imglib/no.png"))); // NOI18N
        jLabel5.setText("Close");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("DOSRocket Alpha build x86-64-mswindows © 2014 Mayukh Nair");

        listerine.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Game list", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N
        listerine.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        listerine.setModel(new DefaultListModel());
        listerine.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listerine.setToolTipText("");
        listerine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listerineMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(listerine);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Game information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton3.setText("Voice control");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DOSBox VM settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
        });

        fullscreencheck.setBackground(new java.awt.Color(255, 255, 255));
        fullscreencheck.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        fullscreencheck.setText("Go fullscreen");
        fullscreencheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullscreencheckMouseEntered(evt);
            }
        });
        fullscreencheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullscreencheckActionPerformed(evt);
            }
        });

        keymappercheck.setBackground(new java.awt.Color(255, 255, 255));
        keymappercheck.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        keymappercheck.setText("Use keymapper");
        keymappercheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                keymappercheckMouseEntered(evt);
            }
        });

        socketcheck.setBackground(new java.awt.Color(255, 255, 255));
        socketcheck.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        socketcheck.setText("Use nullmodem emulation");
        socketcheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                socketcheckMouseEntered(evt);
            }
        });

        noconsolelog.setBackground(new java.awt.Color(255, 255, 255));
        noconsolelog.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        noconsolelog.setText("Hide console log");
        noconsolelog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noconsolelogMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullscreencheck)
                    .addComponent(keymappercheck)
                    .addComponent(socketcheck)
                    .addComponent(noconsolelog))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fullscreencheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(keymappercheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(socketcheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(noconsolelog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Guide", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        guidebold.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        guidebold.setText("DOSRocket Guide will assist you!");

        guidetext.setEditable(false);
        guidetext.setColumns(20);
        guidetext.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        guidetext.setLineWrap(true);
        guidetext.setRows(5);
        guidetext.setText("Just hover your mouse on any \ncomponent in the DOSRocket \nwindow. Help text will \nautomatically come up here.");
        guidetext.setBorder(null);
        jScrollPane2.setViewportView(guidetext);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(guidebold)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guidebold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Voice control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        micicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imglib/micidle.png"))); // NOI18N
        micicon.setToolTipText("Tap the mic!");
        micicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miciconMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel8.setText("Format: open <name of the game>");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel9.setText("You have 5 seconds.");

        resp.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        resp.setText("<null>");

        conf.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        conf.setText("<null>");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel12.setText("Recognised output:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel13.setText("Confidence level:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conf)
                    .addComponent(resp))
                .addGap(66, 66, 66))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(micicon))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(micicon)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resp)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conf)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FrameWindowBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FrameWindowBar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jButton3))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void FrameWindowBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameWindowBarMouseDragged
        // TODO add your handling code here:
        int x,y;
        x=evt.getXOnScreen();
        y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_FrameWindowBarMouseDragged

    private void FrameWindowBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameWindowBarMousePressed
        // TODO add your handling code here:
        xmouse=evt.getX();
        ymouse=evt.getY();
        
    }//GEN-LAST:event_FrameWindowBarMousePressed


  

    private void FrameWindowBarComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_FrameWindowBarComponentShown
        // TODO add your handling code here:
     
    }//GEN-LAST:event_FrameWindowBarComponentShown

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // Shit fails to do anything. Precisely why I hate Java-
        // it promises you something else and delivers something else.
        this.setLocation(330,162);
    }//GEN-LAST:event_formFocusGained

    private void fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusGained
        // TODO add your handling code here:
        fname.setForeground(Color.BLACK);
        fname.setFont(isFocused);
        String p1=fname.getText();
        if(p1.equals("The name of the game")){
           fname.setText(""); 
        }
        
    }//GEN-LAST:event_fnameFocusGained

    private void fdevFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fdevFocusGained
        // TODO add your handling code here:
         fdev.setForeground(Color.BLACK);
        fdev.setFont(isFocused);
        String p2=fdev.getText();
        if(p2.equals("The developer/creator of the game")){
           fdev.setText(""); 
        }
    }//GEN-LAST:event_fdevFocusGained

    private void fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_fnameFocusLost

    private void fdevFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fdevFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_fdevFocusLost

    private void flocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_flocFocusGained
        // TODO add your handling code here:
        String p3=floc.getText();
        if(p3.equals("Where is the main .exe file of the game stored?")){
            floc.setText("");
        }
        floc.setForeground(Color.BLACK);
        floc.setFont(isFocused);
        
    }//GEN-LAST:event_flocFocusGained

    private void flocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_flocFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_flocFocusLost

    private void FrameWindowBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FrameWindowBarFocusLost
        // TODO add your handling code here:
        FrameWindowBar.setForeground(Color.LIGHT_GRAY);
        FrameWindowBar.setFont(notfocused);
        FrameWindowBar.setText("DOSRocket, the DOSBox front-end");
    }//GEN-LAST:event_FrameWindowBarFocusLost

    private void browsebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebuttonActionPerformed
        // TODO add your handling code here:
        JFileChooser browze = new JFileChooser();
        int returnval=browze.showOpenDialog(this);
        if(returnval==JFileChooser.APPROVE_OPTION)
        {
        File target=browze.getSelectedFile();
            filepat=target.getParent();
            String yo=filepat.replace("\\","\\\\\\");
            filenam=target.getName();
             floc.setForeground(Color.BLACK);
             floc.setFont(isFocused);
             floc.setText(yo);
             
        }
        System.out.println(filepat);
    }//GEN-LAST:event_browsebuttonActionPerformed

    private void SaveConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveConfigButtonActionPerformed
        // Deals with the database I/O. Checks if a "dosrocket" database is
        // sitting in the "mysql" database that is on every MySQL installation.
        // If not, creates one for future use. Grabs user input from text fields
        // and records it to the database. The new entry is now loaded with the
        // existing entries in the list.
      Thread SaveConfigThread=new Thread(new Runnable()
      {
          public void run()
          {
              boolean k=true;
        try{
            Class.forName("java.sql.Driver");
            con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","root");
            st=con.createStatement();
        }
        catch (ClassNotFoundException | SQLException ex) {
            String errstring=null;    
            
       
           
            System.out.println("Error at point one: "+ex.getMessage()+" Aborting.\n");
                k=false;
            }
       
        if(k){
            System.out.println("Successfully connected to MySQL Server\nSearching for Database...\n");
                String query = "SELECT table_name FROM INFORMATION_SCHEMA.tables WHERE table_name='dosrocket';";
                try {
                    ras = st.executeQuery(query);
                
                if(ras.first()){
                        System.out.println("Database Found. Connecting...Connected Succcessfully.\n");
                    }
                else{
                    st.executeUpdate("create table dosrocket(name varchar(50) PRIMARY KEY,developer varchar(50), filepath varchar(5000),filename varchar(256))");
                }
               
        }
                catch(SQLException e){
                    System.out.println("Error at point 2: "+e.getMessage());
                }
       
        }
        try{
        String filename=fname.getText();
        String filedev=fdev.getText();
        String filelocn=floc.getText();
        con.createStatement();
        String query="insert into dosrocket values('"+filename+"','"+filedev+"','"+filelocn+"','"+filenam+"')";
        int yo=st.executeUpdate(query);
        
        }
        catch(SQLException e){
            System.out.println("Error at point 3");
            e.printStackTrace();
        }
         try{
     String que="select name from dosrocket";
  
      ras = st.executeQuery(que);
        DefaultListModel dlm=(DefaultListModel)listerine.getModel();
        dlm.removeAllElements();
        while(ras.next()){
                
                
                dlm.addElement(ras.getString(1));
            }
        
        }
        catch(SQLException e){
            System.out.println("Error at point 4");
            e.printStackTrace();
        }
        
          }
      }
      );
      SaveConfigThread.start();
      
      
    }//GEN-LAST:event_SaveConfigButtonActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // Of course, get rid of the program!
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // Set JFrame to given coordinates. Oh wait, why am I 
        // telling a JPanel to do this?
        this.setLocation(330,262);
    }//GEN-LAST:event_jPanel1FocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // This thread grabs data for selected game from SQL Database and
        // passes it on to the Apache Commons Exec API to call DOSBox
        // and provide required parameters.
        Thread RunGameThread=new Thread(new Runnable()
        {
            public void run(){
                String selgame=listerine.getSelectedValue().toString();
        String qu="select filename,filepath from dosrocket where name="+"'"+selgame+"'";
        String gname=null,gpath=null;
        try{
                ras=st.executeQuery(qu);
                while(ras.next()){
                    gname=ras.getString(1);
                  
                    System.out.println(gname);
                gpath=ras.getString(2);
                pop=gpath.replace("\\", "\\\\");
                System.out.println(pop);
                }
                File conffile=new File("C://Windows//Temp//dosboxconfig.conf");
                FileOutputStream fp=new FileOutputStream(conffile);
                String conf="[autoexec] \n"
                        + "mount c "+pop+"\n"
                        + "c: \n"
                        + gname;
                System.out.println(conf);
                try{
                    conffile.createNewFile();
                    byte[] confbytes=conf.getBytes();
                    fp.write(confbytes);
                    fp.flush();
                    fp.close();
                    conffile.deleteOnExit();
                }
                catch(IOException e){
                    e.printStackTrace();
                }
                
                
                
             String cdcommand="C:////Program Files////DOSBox-0.74////dosbox.exe -conf C:////Windows////Temp////dosboxconfig.conf";
              
             CommandLine cmdinstance=CommandLine.parse(cdcommand);
        if(fullscreencheck.isSelected()==true){
            cmdinstance.addArgument("-fullscreen");
        }
        if(keymappercheck.isSelected()==true){
            cmdinstance.addArgument("-startmapper");
        }
        if(socketcheck.isSelected()==true){
            cmdinstance.addArgument("-socket");
        }
        if(noconsolelog.isSelected()==true){
            cmdinstance.addArgument("-noconsole");
        }
        DefaultExecutor exac=new DefaultExecutor();
        
        int exitval2=exac.execute(cmdinstance);
        }
        catch (Exception e){
            e.printStackTrace();
        }
        
    
       
            }
        });
        RunGameThread.start();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Thread MicInputThread=new Thread(new Runnable(){
            public void run(){
                duplo.addResponseListener(new GSpeechResponseListener(){
                    public void OnResponse(GoogleResponse googres){
                        String parsedtext=googres.getResponse();
                        System.out.println(parsedtext);
                    }

                    @Override
                    public void onResponse(GoogleResponse gr) {
                        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }
                });
                micra=new Microphone(FLACFileWriter.FLAC);
                audiofil=new File("AudioTest.flac");
                while(true){
                    try{
                        micra.captureAudioToFile(audiofil);
                        Thread.sleep(5000);
                        micra.close();
                        byte[] data=Files.readAllBytes(micra.getAudioFile().toPath());
                        duplo.recognize(data, (int)micra.getAudioFormat().getSampleRate());
                        micra.getAudioFile().delete();
                    }
                    catch (Exception ex){
                        ex.printStackTrace();
                    }
                }
            }
        });
       MicInputThread.start();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fullscreencheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullscreencheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullscreencheckActionPerformed

    private void FrameWindowBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameWindowBarMouseEntered
        // TODO add your handling code here:
        guidebold.setText("Frame Window Bar");
        guidetext.setText("In absence of the normal window pane, this doubles up as the draggable window bar. Click, hold and drag to drag the window.");
    }//GEN-LAST:event_FrameWindowBarMouseEntered

    private void listerineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listerineMouseEntered
        // TODO add your handling code here:
        guidebold.setText("Game List");
        guidetext.setText("All of your saved game configurations will show up here. Select any one and press 'Run game' to run the game.");
    }//GEN-LAST:event_listerineMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         Thread LoadSavedConfig=new Thread(new Runnable()
     {
        public void run()
        {
        try{
     String que="select name from dosrocket";
  
      ras = st.executeQuery(que);
        DefaultListModel dlm=(DefaultListModel)listerine.getModel();
        dlm.removeAllElements();
        while(ras.next()){
                
                
                dlm.addElement(ras.getString(1));
            }
        
        }
        catch(SQLException e){
            System.out.println("Error at point 4");
            e.printStackTrace();
        }    
        }
             }
             );
         LoadSavedConfig.start();
    }//GEN-LAST:event_formWindowOpened

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        guidebold.setText("Game Information Display");
        guidetext.setText("Information about the game you picked from the adjacent list will come up here.");
    }//GEN-LAST:event_jPanel3MouseEntered

    private void fullscreencheckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullscreencheckMouseEntered
        // TODO add your handling code here:
        guidebold.setText("Fullscreen mode");
        guidetext.setText("Toggle to start DOSBox in fullscreen mode.");
    }//GEN-LAST:event_fullscreencheckMouseEntered

    private void keymappercheckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keymappercheckMouseEntered
        // TODO add your handling code here:
         guidebold.setText("Use keymapper");
        guidetext.setText("Use a keymapper before you start playing. Recommended if your keyboard has an issue.");
    }//GEN-LAST:event_keymappercheckMouseEntered

    private void socketcheckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socketcheckMouseEntered
        // TODO add your handling code here:
         guidebold.setText("Use nullmodem emulation");
        guidetext.setText("Change socket port to nullmodem emulation. Refer to 'Serial Multiplayer' section in the DOSBox User Manual for more help.");
    }//GEN-LAST:event_socketcheckMouseEntered

    private void noconsolelogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noconsolelogMouseEntered
        // TODO add your handling code here:
         guidebold.setText("Hide console log");
        guidetext.setText("Hides the DOSBox Status Window when DOSBox starts up.");
    }//GEN-LAST:event_noconsolelogMouseEntered

    private void browsebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browsebuttonMouseEntered
        // TODO add your handling code here:
         guidebold.setText("Executable File Browser");
        guidetext.setText("Find the required .EXE file of your game using this.");
    }//GEN-LAST:event_browsebuttonMouseEntered

    private void SaveConfigButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveConfigButtonMouseEntered
        // TODO add your handling code here:
         guidebold.setText("Save Configuration");
        guidetext.setText("Once you've filled all details about your game above, hit this to register the entry in the DOSRocket database.");
    }//GEN-LAST:event_SaveConfigButtonMouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
         guidebold.setText("Run game");
        guidetext.setText("Select a game from the loaded game list, select any DOSBox VM options if needed, and then press this button to start DOSBox with your game.");
    }//GEN-LAST:event_jButton2MouseEntered

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
         guidebold.setText("DOSBox VM Settings");
        guidetext.setText("Configure the DOSBox virtual machine environment before running.");
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
         guidebold.setText("Close button");
        guidetext.setText("Click to close DOSRocket. WARNING: If DOSBox game is running, it will close as well.");
    }//GEN-LAST:event_jLabel5MouseEntered

    private void miciconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miciconMouseClicked
        // TODO add your handling code here:
         Thread MicInputThread=new Thread(new Runnable(){
            public void run(){
                duplo.addResponseListener(new GSpeechResponseListener(){
                    public void OnResponse(GoogleResponse googres){
                        String parsedtext=googres.getResponse();
                        resp.setText(parsedtext);
                    }

                    @Override
                    public void onResponse(GoogleResponse gr) {
                        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }
                });
                micra=new Microphone(FLACFileWriter.FLAC);
                audiofil=new File("AudioTest.flac");
                while(true){
                    try{
                        micra.captureAudioToFile(audiofil);
                        Thread.sleep(5000);
                        micra.close();
                        byte[] data=Files.readAllBytes(micra.getAudioFile().toPath());
                        duplo.recognize(data, (int)micra.getAudioFormat().getSampleRate());
                        micra.getAudioFile().delete();
                    }
                    catch (Exception ex){
                        ex.printStackTrace();
                    }
                }
            }
        });
       MicInputThread.start();
    }//GEN-LAST:event_miciconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrameWindowBar;
    private javax.swing.JButton SaveConfigButton;
    private javax.swing.JButton browsebutton;
    private javax.swing.JLabel conf;
    private javax.swing.JTextField fdev;
    private javax.swing.JTextField floc;
    private javax.swing.JTextField fname;
    private javax.swing.JCheckBox fullscreencheck;
    private javax.swing.JLabel guidebold;
    private javax.swing.JTextArea guidetext;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox keymappercheck;
    private javax.swing.JList listerine;
    private javax.swing.JLabel micicon;
    private javax.swing.JCheckBox noconsolelog;
    private javax.swing.JLabel resp;
    private javax.swing.JCheckBox socketcheck;
    // End of variables declaration//GEN-END:variables

    
}

